name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Activity Overview and Habits
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: RavinduWathsula
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 30
          plugin_habits_facts: no
          config_timezone: Asia/Colombo
          output_action: commit
          committer_branch: output
